// Per-word image subjects for tools/gen-images.js.
// Default subject is the English meaning (first alternative before " / ").
// OVERRIDES give a concrete scene for verbs, phrases and abstract words.
// NO_IMAGE lists words that cannot be pictured — they get no picture card.

export const STYLE =
  'simple flat cartoon illustration, single subject centered, plain white background, bright friendly colours, clean vector style for a children\'s picture dictionary, no text, no letters, no numbers';

export const NO_IMAGE = new Set([
  'oui', 'non', 'je', 'tu', 'il', 'elle', 'nous', 'vous', 'ils', 'comment', 'quoi', 'ou', 'qui', 'quand', 'pourquoi',
  'parce-que', 'et', 'ou-or', 'mais', 'avec', 'sans', 'ici', 'la', 'tres', 'beaucoup', 'un-peu', 'aussi', 'maintenant',
  'toujours', 'jamais', 'peut-etre', 'd-accord', 'je-ne-sais-pas', 'je-ne-comprends-pas', 'ca-va', 'ca-va-bien',
  'de-rien', 'pardon', 'excusez-moi', 'je-m-appelle', 'bienvenue', 'a-bientot', 'bonne-chance',
  'etre', 'avoir', 'pouvoir', 'savoir', 'vouloir', 'nom', 'age', 'gens', 'temps', 'mot', 'phrase', 'question', 'reponse',
  'combien', 'nombre', 'couleur', 'premier', 'deuxieme', 'troisieme', 'mille', 'cent',
  'clair', 'fonce', 'nouveau', 'bon', 'mauvais', 'facile', 'difficile', 'pres', 'loin', 'haut', 'bas', 'gauche', 'droite',
  'onze', 'douze', 'treize', 'quatorze', 'quinze', 'seize', 'dix-sept', 'dix-huit', 'dix-neuf', 'vingt', 'trente',
  'quarante', 'cinquante', 'zero', 'un', 'deux', 'trois', 'quatre', 'cinq', 'six', 'sept', 'huit', 'neuf', 'dix',
  'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche', 'semaine', 'mois', 'annee', 'minute', 'heure',
  'aujourd-hui', 'demain', 'hier', 'week-end', 'monde',
]);

export const OVERRIDES = {
  // greetings
  bonjour: 'a smiling child waving hello in the morning sunshine',
  salut: 'two children giving each other a friendly high five',
  bonsoir: 'a child waving hello at dusk with an orange sunset sky',
  'bonne-nuit': 'a child in pyjamas in bed saying goodnight, moon in the window',
  'au-revoir': 'a child waving goodbye to a departing bus',
  merci: 'a child holding a gift and saying thank you with a big smile',
  's-il-te-plait': 'a child with hands together politely asking please',
  'joyeux-anniversaire': 'a birthday cake with candles and a party hat',
  monsieur: 'a friendly man in a suit and hat',
  madame: 'a friendly woman in a smart dress',
  // family / people
  famille: 'a happy family of four standing together',
  mere: 'a smiling mother',
  pere: 'a smiling father',
  maman: 'a mother hugging her small child',
  papa: 'a father carrying his child on his shoulders',
  parents: 'a mother and father standing together',
  soeur: 'a young girl, big sister',
  frere: 'a young boy, big brother',
  fille: 'a young girl',
  garcon: 'a young boy',
  fils: 'a father with his son',
  'grand-mere': 'a smiling grandmother with grey hair and glasses',
  'grand-pere': 'a smiling grandfather with a beard and glasses',
  tante: 'a friendly aunt waving',
  oncle: 'a friendly uncle waving',
  cousin: 'a boy cousin smiling',
  cousine: 'a girl cousin smiling',
  ami: 'two boys who are best friends with arms around shoulders',
  amie: 'two girls who are best friends holding hands',
  homme: 'a man',
  femme: 'a woman',
  enfant: 'a small child',
  voisin: 'a neighbour waving over a garden fence',
  docteur: 'a doctor with a stethoscope',
  professeur: 'a teacher at a blackboard',
  // animals with ambiguous names
  poulet: 'a roast chicken on a plate',
  // food
  nourriture: 'a table full of food',
  salade: 'a bowl of green salad',
  'pomme-de-terre': 'a potato',
  viande: 'a piece of meat, a steak',
  frites: 'a portion of chips / french fries',
  bonbon: 'a colourful wrapped sweet',
  glace: 'an ice cream cone',
  crepe: 'a thin pancake with a fruit topping',
  sucre: 'a bowl of sugar cubes',
  sel: 'a salt shaker',
  'petit-dejeuner': 'a breakfast table with cereal, juice and toast',
  dejeuner: 'a lunch box with a sandwich and apple',
  diner: 'a family eating dinner at a table in the evening',
  'j-ai-faim': 'a hungry child holding an empty plate, tummy rumbling',
  'j-ai-soif': 'a thirsty child reaching for a glass of water',
  delicieux: 'a child licking lips over a delicious meal',
  'bon-appetit': 'a child with a knife and fork about to eat happily',
  // colours
  rouge: 'a red apple, a red ball and a red car',
  bleu: 'a blue ball, blue paint splash and blue butterfly',
  vert: 'a green leaf, green frog and green ball',
  jaune: 'a yellow sun, yellow banana and yellow ball',
  'orange-orange-colour': 'an orange paint splash and orange ball',
  violet: 'a purple paint splash, purple grapes and purple ball',
  rose: 'a pink flower, pink paint splash and pink ball',
  marron: 'a brown paint splash, brown bear and brown chestnut',
  noir: 'a black cat and black paint splash',
  blanc: 'a white snowman on a light grey background',
  gris: 'a grey elephant and grey paint splash',
  dore: 'a golden trophy and gold coins',
  argente: 'a silver medal and silver spoon',
  multicolore: 'a rainbow of colourful paint splashes',
  // body
  corps: 'a child standing showing the whole body',
  tete: 'a child\'s head',
  cheveux: 'long flowing hair on a girl',
  visage: 'a smiling face',
  oeil: 'a single eye',
  yeux: 'a pair of eyes',
  langue: 'a child sticking out their tongue',
  cou: 'the neck of a person',
  epaule: 'a person pointing at their shoulder',
  bras: 'an arm',
  main: 'an open hand',
  doigt: 'a pointing finger',
  ventre: 'a child patting their tummy',
  dos: 'the back of a person',
  jambe: 'a leg',
  genou: 'a bent knee',
  pied: 'a foot',
  coeur: 'a red heart',
  cerveau: 'a brain',
  os: 'a bone',
  sang: 'a drop of blood',
  peau: 'a hand touching skin on an arm',
  'j-ai-mal': 'a child holding a sore knee with a plaster',
  malade: 'a sick child in bed with a thermometer',
  fatigue: 'a tired child yawning',
  content: 'a very happy child jumping with joy',
  triste: 'a sad child with a tear',
  'en-colere': 'an angry child with crossed arms',
  peur: 'a scared child hiding under a blanket',
  // home
  maison: 'a house with a red roof',
  appartement: 'an apartment building with balconies',
  chambre: 'a child\'s bedroom with a bed',
  lit: 'a bed',
  cuisine: 'a kitchen with a cooker',
  salon: 'a living room with a sofa and tv',
  'salle-de-bain': 'a bathroom with a bathtub',
  toilettes: 'a toilet',
  jardin: 'a garden with flowers and a tree',
  escalier: 'a staircase',
  verre: 'a drinking glass of water',
  tasse: 'a cup with a handle',
  frigo: 'a fridge',
  poubelle: 'a rubbish bin',
  jouet: 'a pile of toys',
  ballon: 'a red ball',
  cadeau: 'a wrapped gift box with a bow',
  boite: 'a cardboard box',
  rue: 'a street with houses',
  ville: 'a city skyline',
  magasin: 'a shop front',
  parc: 'a park with trees and a bench',
  argent: 'coins and banknotes',
  // clothes
  vetements: 'a pile of folded clothes',
  pull: 'a knitted jumper',
  short: 'a pair of shorts',
  veste: 'a jacket',
  chaussures: 'a pair of shoes',
  bottes: 'a pair of boots',
  chaussettes: 'a pair of socks',
  chapeau: 'a hat',
  lunettes: 'a pair of glasses',
  pyjama: 'pyjamas',
  'maillot-de-bain': 'a swimsuit',
  sac: 'a handbag',
  montre: 'a wristwatch',
  couronne: 'a golden crown',
  // school
  ecole: 'a school building',
  classe: 'a classroom with desks',
  eleve: 'a pupil with a backpack',
  cahier: 'a notebook',
  gomme: 'a pencil eraser',
  regle: 'a ruler',
  colle: 'a glue stick',
  tableau: 'a blackboard',
  bureau: 'a desk',
  devoir: 'a child doing homework at a desk',
  lettre: 'an envelope letter',
  histoire: 'an open storybook',
  musique: 'musical notes and a guitar',
  chanson: 'a child singing into a microphone',
  dessin: 'a child\'s drawing on paper with crayons',
  sport: 'sports equipment: ball, racket and trainers',
  football: 'a football',
  natation: 'a child swimming in a pool',
  danse: 'a girl dancing',
  jeu: 'a board game with dice',
  recreation: 'children playing in a playground',
  bibliotheque: 'a library with bookshelves',
  anglais: 'the British flag',
  francais: 'the French flag',
  suedois: 'the Swedish flag',
  mathematiques: 'a calculator and plus minus signs',
  science: 'a science flask and test tubes',
  // weather / time / nature
  soleil: 'a bright sun',
  pluie: 'rain falling from a cloud',
  neige: 'snow falling with a snowman',
  vent: 'wind blowing leaves',
  nuage: 'a fluffy cloud',
  orage: 'a storm cloud with lightning',
  'arc-en-ciel': 'a rainbow',
  'il-fait-chaud': 'a hot sunny day with a child sweating and an ice cream',
  'il-fait-froid': 'a cold snowy day with a child in a scarf shivering',
  'il-pleut': 'a child with an umbrella in the rain',
  printemps: 'spring blossoms and a bird',
  ete: 'a summer beach with sun',
  automne: 'autumn tree with falling orange leaves',
  hiver: 'a winter snowy scene with a snowman',
  jour: 'a bright sunny sky',
  nuit: 'a starry night sky with the moon',
  matin: 'a sunrise with a rooster',
  'apres-midi': 'an afternoon sun over a park',
  soir: 'an evening sunset',
  lune: 'a crescent moon',
  etoile: 'a yellow star',
  ciel: 'a blue sky with clouds',
  mer: 'the sea with waves',
  plage: 'a sandy beach with a bucket and spade',
  montagne: 'a mountain with a snowy peak',
  foret: 'a forest of trees',
  arbre: 'a tree',
  fleur: 'a flower',
  herbe: 'green grass',
  riviere: 'a river',
  feu: 'a campfire',
  terre: 'planet earth',
  fete: 'a party with balloons and confetti',
  noel: 'a decorated Christmas tree',
  vacances: 'a suitcase and sunglasses on holiday',
  // verbs
  aller: 'a child walking through a door going somewhere',
  venir: 'a child waving and coming towards the viewer',
  faire: 'a child building something with tools',
  dire: 'a child speaking with a speech bubble',
  parler: 'two children talking to each other',
  voir: 'a child looking through binoculars',
  regarder: 'a child watching television',
  ecouter: 'a child listening with headphones',
  entendre: 'a child cupping a hand to their ear to hear',
  manger: 'a child eating a sandwich',
  boire: 'a child drinking from a glass',
  dormir: 'a child sleeping in bed',
  jouer: 'a child playing with a ball',
  lire: 'a child reading a book',
  ecrire: 'a child writing with a pencil',
  chanter: 'a child singing',
  danser: 'a child dancing',
  courir: 'a child running',
  marcher: 'a child walking',
  sauter: 'a child jumping high',
  nager: 'a child swimming',
  ouvrir: 'a child opening a door',
  fermer: 'a child closing a door',
  donner: 'a child giving a present to another child',
  prendre: 'a child taking an apple from a bowl',
  aimer: 'a child hugging a teddy bear with hearts',
  penser: 'a child thinking with a thought bubble',
  apprendre: 'a child learning at school with a book and lightbulb',
  comprendre: 'a child with a lightbulb idea above their head',
  acheter: 'a child buying something at a shop counter',
  habiter: 'a child standing in front of their home',
  travailler: 'a person working at a desk with a computer',
  attendre: 'a child waiting at a bus stop looking at a watch',
  chercher: 'a child searching with a magnifying glass',
  trouver: 'a child finding a coin and holding it up happily',
  aider: 'a child helping another child get up',
  rire: 'a child laughing loudly',
  pleurer: 'a child crying',
  dessiner: 'a child drawing with crayons',
  // adjectives
  grand: 'a very tall giraffe next to a small mouse, arrow pointing at the giraffe',
  petit: 'a tiny mouse next to a big elephant, arrow pointing at the mouse',
  beau: 'a beautiful peacock',
  joli: 'a pretty flower bouquet',
  vieux: 'an old man with a walking stick',
  jeune: 'a young child',
  chaud: 'a hot cup of steaming cocoa and sun',
  froid: 'an ice cube and a snowflake',
  rapide: 'a fast rabbit racing',
  lent: 'a slow tortoise',
  fort: 'a strong person lifting weights',
  gentil: 'a kind child sharing with a friend',
  mechant: 'a naughty child pulling a face',
  drole: 'a funny clown',
  propre: 'a sparkling clean plate',
  sale: 'a muddy dirty dog',
  plein: 'a glass full of juice',
  vide: 'an empty glass',
  ouvert: 'an open door',
  ferme: 'a closed door',
};
