// Source of truth for the starter dictionary. Run `node tools/build-words.js` to emit words.json.
// Format per line: [article, french, english, emoji|null]
// Units are ordered by usefulness; rank is assigned by position (unit order, then line order).

export const UNITS = [
  { id: 1, name: 'Greetings & basics', sv: 'Hälsningar & grunder', emoji: '👋' },
  { id: 2, name: 'Family & people', sv: 'Familj & människor', emoji: '👨‍👩‍👧' },
  { id: 3, name: 'Animals', sv: 'Djur', emoji: '🐾' },
  { id: 4, name: 'Food & drink', sv: 'Mat & dryck', emoji: '🍎' },
  { id: 5, name: 'Colours', sv: 'Färger', emoji: '🎨' },
  { id: 6, name: 'Numbers', sv: 'Siffror', emoji: '🔢' },
  { id: 7, name: 'Body', sv: 'Kroppen', emoji: '🖐️' },
  { id: 8, name: 'Home', sv: 'Hemma', emoji: '🏠' },
  { id: 9, name: 'Clothes', sv: 'Kläder', emoji: '👕' },
  { id: 10, name: 'School', sv: 'Skolan', emoji: '🏫' },
  { id: 11, name: 'Weather, time & nature', sv: 'Väder, tid & natur', emoji: '🌤️' },
  { id: 12, name: 'Verbs & adjectives', sv: 'Verb & adjektiv', emoji: '⚡' },
];

const _ = null;

export const WORDS = {
  1: [
    [_, 'bonjour', 'hello / good day', '👋'],
    [_, 'salut', 'hi', '🙋'],
    [_, 'bonsoir', 'good evening', '🌆'],
    [_, 'bonne nuit', 'good night', '🌙'],
    [_, 'au revoir', 'goodbye', '👋'],
    [_, 'oui', 'yes', '👍'],
    [_, 'non', 'no', '👎'],
    [_, 'merci', 'thank you', '🙏'],
    [_, "s'il te plaît", 'please', '🥺'],
    [_, 'de rien', "you're welcome", '😊'],
    [_, 'pardon', 'sorry / excuse me', '😬'],
    [_, 'excusez-moi', 'excuse me', '🙇'],
    [_, 'ça va ?', 'how are you?', '🤔'],
    [_, 'ça va bien', "I'm fine", '😃'],
    [_, 'je', 'I', '🙋'],
    [_, 'tu', 'you', '👉'],
    [_, 'il', 'he', '👦'],
    [_, 'elle', 'she', '👧'],
    [_, 'nous', 'we', '👫'],
    [_, 'vous', 'you (plural / polite)', '👥'],
    [_, 'ils', 'they', '👬'],
    [_, 'je m\'appelle', 'my name is', '🏷️'],
    [_, 'comment', 'how', '❓'],
    [_, 'quoi', 'what', '❓'],
    [_, 'où', 'where', '📍'],
    [_, 'qui', 'who', '👤'],
    [_, 'quand', 'when', '⏰'],
    [_, 'pourquoi', 'why', '🤷'],
    [_, 'parce que', 'because', '💡'],
    [_, 'et', 'and', '➕'],
    [_, 'ou', 'or', '🔀'],
    [_, 'mais', 'but', '↩️'],
    [_, 'avec', 'with', '🤝'],
    [_, 'sans', 'without', '🚫'],
    [_, 'ici', 'here', '📍'],
    [_, 'là', 'there', '👉'],
    [_, 'très', 'very', '💯'],
    [_, 'beaucoup', 'a lot', '🔝'],
    [_, 'un peu', 'a little', '🤏'],
    [_, 'aussi', 'also / too', '➕'],
    [_, 'maintenant', 'now', '⏱️'],
    [_, 'toujours', 'always', '♾️'],
    [_, 'jamais', 'never', '🚫'],
    [_, 'peut-être', 'maybe', '🤷'],
    [_, "d'accord", 'okay / agreed', '👌'],
    [_, 'bienvenue', 'welcome', '🎉'],
    [_, 'à bientôt', 'see you soon', '👋'],
    [_, 'bonne chance', 'good luck', '🍀'],
    [_, 'joyeux anniversaire', 'happy birthday', '🎂'],
    [_, "je ne sais pas", "I don't know", '🤷'],
    [_, "je ne comprends pas", "I don't understand", '😕'],
    [_, 'monsieur', 'sir / Mr', '🤵'],
    [_, 'madame', 'madam / Mrs', '👩'],
  ],
  2: [
    ['la', 'famille', 'family', '👨‍👩‍👧‍👦'],
    ['la', 'mère', 'mother', '👩'],
    ['le', 'père', 'father', '👨'],
    ['la', 'maman', 'mum', '🤱'],
    ['le', 'papa', 'dad', '👨‍🍼'],
    ['les', 'parents', 'parents', '👫'],
    ['la', 'sœur', 'sister', '👧'],
    ['le', 'frère', 'brother', '👦'],
    ['la', 'fille', 'girl / daughter', '👧'],
    ['le', 'garçon', 'boy', '👦'],
    ['le', 'fils', 'son', '👦'],
    ['le', 'bébé', 'baby', '👶'],
    ['la', 'grand-mère', 'grandmother', '👵'],
    ['le', 'grand-père', 'grandfather', '👴'],
    ['la', 'tante', 'aunt', '👩‍🦱'],
    ["l'", 'oncle', 'uncle', '👨‍🦱'],
    ['le', 'cousin', 'cousin (boy)', '🧒'],
    ['la', 'cousine', 'cousin (girl)', '👧'],
    ["l'", 'ami', 'friend (boy)', '🧑‍🤝‍🧑'],
    ["l'", 'amie', 'friend (girl)', '👭'],
    ["l'", 'homme', 'man', '👨'],
    ['la', 'femme', 'woman / wife', '👩'],
    ["l'", 'enfant', 'child', '🧒'],
    ['les', 'gens', 'people', '👥'],
    ['le', 'nom', 'name', '🏷️'],
    ["l'", 'âge', 'age', '🎂'],
    ['le', 'voisin', 'neighbour', '🏘️'],
    ['le', 'docteur', 'doctor', '🧑‍⚕️'],
    ['le', 'professeur', 'teacher', '🧑‍🏫'],
    ['le', 'roi', 'king', '🤴'],
    ['la', 'reine', 'queen', '👸'],
    ['la', 'princesse', 'princess', '👸'],
    ['le', 'prince', 'prince', '🤴'],
  ],
  3: [
    ["l'", 'animal', 'animal', '🐾'],
    ['le', 'chien', 'dog', '🐕'],
    ['le', 'chat', 'cat', '🐈'],
    ['le', 'chaton', 'kitten', '🐱'],
    ['le', 'chiot', 'puppy', '🐶'],
    ['le', 'cheval', 'horse', '🐴'],
    ['la', 'vache', 'cow', '🐄'],
    ['le', 'cochon', 'pig', '🐖'],
    ['le', 'mouton', 'sheep', '🐑'],
    ['la', 'chèvre', 'goat', '🐐'],
    ['la', 'poule', 'hen', '🐔'],
    ['le', 'coq', 'rooster', '🐓'],
    ['le', 'canard', 'duck', '🦆'],
    ['le', 'lapin', 'rabbit', '🐰'],
    ['la', 'souris', 'mouse', '🐭'],
    ["l'", 'oiseau', 'bird', '🐦'],
    ['le', 'poisson', 'fish', '🐟'],
    ['la', 'grenouille', 'frog', '🐸'],
    ['la', 'tortue', 'turtle', '🐢'],
    ['le', 'serpent', 'snake', '🐍'],
    ["l'", 'ours', 'bear', '🐻'],
    ['le', 'loup', 'wolf', '🐺'],
    ['le', 'renard', 'fox', '🦊'],
    ['le', 'lion', 'lion', '🦁'],
    ['le', 'tigre', 'tiger', '🐯'],
    ["l'", 'éléphant', 'elephant', '🐘'],
    ['la', 'girafe', 'giraffe', '🦒'],
    ['le', 'singe', 'monkey', '🐒'],
    ['le', 'zèbre', 'zebra', '🦓'],
    ['le', 'kangourou', 'kangaroo', '🦘'],
    ['le', 'pingouin', 'penguin', '🐧'],
    ['le', 'dauphin', 'dolphin', '🐬'],
    ['la', 'baleine', 'whale', '🐳'],
    ['le', 'requin', 'shark', '🦈'],
    ['le', 'papillon', 'butterfly', '🦋'],
    ["l'", 'abeille', 'bee', '🐝'],
    ['la', 'fourmi', 'ant', '🐜'],
    ["l'", 'araignée', 'spider', '🕷️'],
    ['la', 'coccinelle', 'ladybird', '🐞'],
    ['le', 'hibou', 'owl', '🦉'],
    ["l'", 'écureuil', 'squirrel', '🐿️'],
    ['le', 'hérisson', 'hedgehog', '🦔'],
    ['le', 'cerf', 'deer', '🦌'],
    ['le', 'dinosaure', 'dinosaur', '🦖'],
    ['la', 'licorne', 'unicorn', '🦄'],
    ['le', 'dragon', 'dragon', '🐉'],
  ],
  4: [
    ['la', 'nourriture', 'food', '🍽️'],
    ["l'", 'eau', 'water', '💧'],
    ['le', 'lait', 'milk', '🥛'],
    ['le', 'jus', 'juice', '🧃'],
    ['le', 'pain', 'bread', '🍞'],
    ['le', 'fromage', 'cheese', '🧀'],
    ['le', 'beurre', 'butter', '🧈'],
    ["l'", 'œuf', 'egg', '🥚'],
    ['la', 'pomme', 'apple', '🍎'],
    ['la', 'banane', 'banana', '🍌'],
    ['la', 'fraise', 'strawberry', '🍓'],
    ["l'", 'orange', 'orange', '🍊'],
    ['le', 'citron', 'lemon', '🍋'],
    ['le', 'raisin', 'grapes', '🍇'],
    ['la', 'poire', 'pear', '🍐'],
    ['la', 'pêche', 'peach', '🍑'],
    ['la', 'cerise', 'cherry', '🍒'],
    ['la', 'pastèque', 'watermelon', '🍉'],
    ["l'", 'ananas', 'pineapple', '🍍'],
    ['la', 'carotte', 'carrot', '🥕'],
    ['la', 'tomate', 'tomato', '🍅'],
    ['la', 'pomme de terre', 'potato', '🥔'],
    ['la', 'salade', 'salad / lettuce', '🥗'],
    ['le', 'maïs', 'corn', '🌽'],
    ['le', 'brocoli', 'broccoli', '🥦'],
    ['le', 'champignon', 'mushroom', '🍄'],
    ['la', 'viande', 'meat', '🥩'],
    ['le', 'poulet', 'chicken (meat)', '🍗'],
    ['le', 'jambon', 'ham', '🍖'],
    ['le', 'riz', 'rice', '🍚'],
    ['les', 'pâtes', 'pasta', '🍝'],
    ['la', 'pizza', 'pizza', '🍕'],
    ['la', 'soupe', 'soup', '🍲'],
    ['le', 'sandwich', 'sandwich', '🥪'],
    ['les', 'frites', 'chips / fries', '🍟'],
    ['le', 'gâteau', 'cake', '🍰'],
    ['le', 'chocolat', 'chocolate', '🍫'],
    ['le', 'bonbon', 'sweet / candy', '🍬'],
    ['la', 'glace', 'ice cream', '🍦'],
    ['le', 'biscuit', 'biscuit / cookie', '🍪'],
    ['la', 'crêpe', 'pancake', '🥞'],
    ['le', 'croissant', 'croissant', '🥐'],
    ['le', 'sucre', 'sugar', '🍬'],
    ['le', 'sel', 'salt', '🧂'],
    ['le', 'miel', 'honey', '🍯'],
    ['le', 'café', 'coffee', '☕'],
    ['le', 'thé', 'tea', '🍵'],
    ['le', 'petit-déjeuner', 'breakfast', '🥣'],
    ['le', 'déjeuner', 'lunch', '🍱'],
    ['le', 'dîner', 'dinner', '🍽️'],
    [_, "j'ai faim", "I'm hungry", '😋'],
    [_, "j'ai soif", "I'm thirsty", '🥤'],
    [_, 'délicieux', 'delicious', '😋'],
    [_, 'bon appétit', 'enjoy your meal', '🍴'],
  ],
  5: [
    ['la', 'couleur', 'colour', '🎨'],
    [_, 'rouge', 'red', '🔴'],
    [_, 'bleu', 'blue', '🔵'],
    [_, 'vert', 'green', '🟢'],
    [_, 'jaune', 'yellow', '🟡'],
    [_, 'orange', 'orange (colour)', '🟠'],
    [_, 'violet', 'purple', '🟣'],
    [_, 'rose', 'pink', '🌸'],
    [_, 'marron', 'brown', '🟤'],
    [_, 'noir', 'black', '⚫'],
    [_, 'blanc', 'white', '⚪'],
    [_, 'gris', 'grey', '🩶'],
    [_, 'doré', 'golden', '🥇'],
    [_, 'argenté', 'silver', '🥈'],
    [_, 'clair', 'light (colour)', '🌕'],
    [_, 'foncé', 'dark (colour)', '🌑'],
    [_, 'multicolore', 'multicoloured', '🌈'],
  ],
  6: [
    ['le', 'nombre', 'number', '🔢'],
    [_, 'zéro', 'zero', '0️⃣'],
    [_, 'un', 'one', '1️⃣'],
    [_, 'deux', 'two', '2️⃣'],
    [_, 'trois', 'three', '3️⃣'],
    [_, 'quatre', 'four', '4️⃣'],
    [_, 'cinq', 'five', '5️⃣'],
    [_, 'six', 'six', '6️⃣'],
    [_, 'sept', 'seven', '7️⃣'],
    [_, 'huit', 'eight', '8️⃣'],
    [_, 'neuf', 'nine', '9️⃣'],
    [_, 'dix', 'ten', '🔟'],
    [_, 'onze', 'eleven', _],
    [_, 'douze', 'twelve', _],
    [_, 'treize', 'thirteen', _],
    [_, 'quatorze', 'fourteen', _],
    [_, 'quinze', 'fifteen', _],
    [_, 'seize', 'sixteen', _],
    [_, 'dix-sept', 'seventeen', _],
    [_, 'dix-huit', 'eighteen', _],
    [_, 'dix-neuf', 'nineteen', _],
    [_, 'vingt', 'twenty', _],
    [_, 'trente', 'thirty', _],
    [_, 'quarante', 'forty', _],
    [_, 'cinquante', 'fifty', _],
    [_, 'cent', 'hundred', '💯'],
    [_, 'mille', 'thousand', _],
    [_, 'premier', 'first', '🥇'],
    [_, 'deuxième', 'second', '🥈'],
    [_, 'troisième', 'third', '🥉'],
    [_, 'combien', 'how many / how much', '🔢'],
  ],
  7: [
    ['le', 'corps', 'body', '🧍'],
    ['la', 'tête', 'head', '🗣️'],
    ['les', 'cheveux', 'hair', '💇'],
    ['le', 'visage', 'face', '🙂'],
    ["l'", 'œil', 'eye', '👁️'],
    ['les', 'yeux', 'eyes', '👀'],
    ['le', 'nez', 'nose', '👃'],
    ['la', 'bouche', 'mouth', '👄'],
    ['la', 'dent', 'tooth', '🦷'],
    ['la', 'langue', 'tongue / language', '👅'],
    ["l'", 'oreille', 'ear', '👂'],
    ['le', 'cou', 'neck', '🧣'],
    ["l'", 'épaule', 'shoulder', '🤷'],
    ['le', 'bras', 'arm', '💪'],
    ['la', 'main', 'hand', '✋'],
    ['le', 'doigt', 'finger', '☝️'],
    ['le', 'ventre', 'tummy / belly', '🫃'],
    ['le', 'dos', 'back', '🔙'],
    ['la', 'jambe', 'leg', '🦵'],
    ['le', 'genou', 'knee', '🦵'],
    ['le', 'pied', 'foot', '🦶'],
    ['le', 'cœur', 'heart', '❤️'],
    ['le', 'cerveau', 'brain', '🧠'],
    ['les', 'os', 'bones', '🦴'],
    ['le', 'sang', 'blood', '🩸'],
    ['la', 'peau', 'skin', '🧴'],
    [_, "j'ai mal", 'it hurts', '🤕'],
    [_, 'malade', 'ill / sick', '🤒'],
    [_, 'fatigué', 'tired', '😴'],
    [_, 'content', 'happy / pleased', '😊'],
    [_, 'triste', 'sad', '😢'],
    [_, 'en colère', 'angry', '😠'],
    [_, 'peur', 'fear / scared', '😨'],
  ],
  8: [
    ['la', 'maison', 'house / home', '🏠'],
    ["l'", 'appartement', 'flat / apartment', '🏢'],
    ['la', 'porte', 'door', '🚪'],
    ['la', 'fenêtre', 'window', '🪟'],
    ['la', 'clé', 'key', '🔑'],
    ['la', 'chambre', 'bedroom', '🛏️'],
    ['le', 'lit', 'bed', '🛏️'],
    ['la', 'cuisine', 'kitchen', '🍳'],
    ['le', 'salon', 'living room', '🛋️'],
    ['la', 'salle de bain', 'bathroom', '🛁'],
    ['les', 'toilettes', 'toilet', '🚽'],
    ['le', 'jardin', 'garden', '🌷'],
    ["l'", 'escalier', 'stairs', '🪜'],
    ['la', 'table', 'table', '🪑'],
    ['la', 'chaise', 'chair', '🪑'],
    ['le', 'canapé', 'sofa', '🛋️'],
    ['la', 'lampe', 'lamp', '💡'],
    ['la', 'télévision', 'television', '📺'],
    ['le', 'téléphone', 'phone', '📱'],
    ["l'", 'ordinateur', 'computer', '💻'],
    ['le', 'miroir', 'mirror', '🪞'],
    ['la', 'douche', 'shower', '🚿'],
    ['le', 'savon', 'soap', '🧼'],
    ['la', 'brosse à dents', 'toothbrush', '🪥'],
    ['la', 'serviette', 'towel', '🧻'],
    ["l'", 'assiette', 'plate', '🍽️'],
    ['le', 'verre', 'glass', '🥛'],
    ['la', 'tasse', 'cup', '☕'],
    ['la', 'fourchette', 'fork', '🍴'],
    ['le', 'couteau', 'knife', '🔪'],
    ['la', 'cuillère', 'spoon', '🥄'],
    ['le', 'frigo', 'fridge', '🧊'],
    ['la', 'poubelle', 'bin', '🗑️'],
    ['le', 'jouet', 'toy', '🧸'],
    ['la', 'poupée', 'doll', '🪆'],
    ['le', 'ballon', 'ball / balloon', '🎈'],
    ['le', 'cadeau', 'present / gift', '🎁'],
    ['la', 'boîte', 'box', '📦'],
    ['la', 'rue', 'street', '🛣️'],
    ['la', 'ville', 'town / city', '🏙️'],
    ['le', 'magasin', 'shop', '🏪'],
    ['le', 'parc', 'park', '🌳'],
    ['la', 'voiture', 'car', '🚗'],
    ['le', 'vélo', 'bike', '🚲'],
    ['le', 'bus', 'bus', '🚌'],
    ['le', 'train', 'train', '🚆'],
    ["l'", 'avion', 'plane', '✈️'],
    ['le', 'bateau', 'boat', '⛵'],
    ["l'", 'argent', 'money', '💰'],
  ],
  9: [
    ['les', 'vêtements', 'clothes', '👚'],
    ['le', 't-shirt', 't-shirt', '👕'],
    ['la', 'chemise', 'shirt', '👔'],
    ['le', 'pull', 'jumper / sweater', '🧶'],
    ['le', 'pantalon', 'trousers', '👖'],
    ['le', 'short', 'shorts', '🩳'],
    ['la', 'jupe', 'skirt', '👗'],
    ['la', 'robe', 'dress', '👗'],
    ['le', 'manteau', 'coat', '🧥'],
    ['la', 'veste', 'jacket', '🧥'],
    ['les', 'chaussures', 'shoes', '👟'],
    ['les', 'bottes', 'boots', '👢'],
    ['les', 'chaussettes', 'socks', '🧦'],
    ['le', 'chapeau', 'hat', '👒'],
    ['la', 'casquette', 'cap', '🧢'],
    ["l'", 'écharpe', 'scarf', '🧣'],
    ['les', 'gants', 'gloves', '🧤'],
    ['les', 'lunettes', 'glasses', '👓'],
    ['le', 'pyjama', 'pyjamas', '🛌'],
    ['le', 'maillot de bain', 'swimsuit', '🩱'],
    ['le', 'sac', 'bag', '👜'],
    ['la', 'montre', 'watch', '⌚'],
    ['la', 'couronne', 'crown', '👑'],
  ],
  10: [
    ["l'", 'école', 'school', '🏫'],
    ['la', 'classe', 'class / classroom', '🧑‍🏫'],
    ["l'", 'élève', 'pupil', '🧒'],
    ['le', 'livre', 'book', '📖'],
    ['le', 'cahier', 'notebook', '📓'],
    ['le', 'stylo', 'pen', '🖊️'],
    ['le', 'crayon', 'pencil', '✏️'],
    ['la', 'gomme', 'rubber / eraser', '🩹'],
    ['la', 'règle', 'ruler', '📏'],
    ['les', 'ciseaux', 'scissors', '✂️'],
    ['la', 'colle', 'glue', '🧴'],
    ['le', 'sac à dos', 'backpack', '🎒'],
    ['le', 'tableau', 'board / painting', '🖼️'],
    ['le', 'bureau', 'desk / office', '🪑'],
    ['la', 'question', 'question', '❓'],
    ['la', 'réponse', 'answer', '💬'],
    ['le', 'devoir', 'homework', '📝'],
    ['la', 'lettre', 'letter', '✉️'],
    ['le', 'mot', 'word', '🔤'],
    ['la', 'phrase', 'sentence', '📝'],
    ["l'", 'histoire', 'story / history', '📚'],
    ['la', 'musique', 'music', '🎵'],
    ['la', 'chanson', 'song', '🎤'],
    ['le', 'dessin', 'drawing', '🎨'],
    ['le', 'sport', 'sport', '⚽'],
    ['le', 'football', 'football', '⚽'],
    ['la', 'natation', 'swimming', '🏊'],
    ['la', 'danse', 'dance', '💃'],
    ['le', 'jeu', 'game', '🎲'],
    ['la', 'récréation', 'break / recess', '🛝'],
    ['la', 'bibliothèque', 'library', '📚'],
    ["l'", 'anglais', 'English', '🇬🇧'],
    ['le', 'français', 'French', '🇫🇷'],
    ['le', 'suédois', 'Swedish', '🇸🇪'],
    ['les', 'mathématiques', 'maths', '➗'],
    ['la', 'science', 'science', '🔬'],
  ],
  11: [
    ['le', 'temps', 'weather / time', '⏳'],
    ['le', 'soleil', 'sun', '☀️'],
    ['la', 'pluie', 'rain', '🌧️'],
    ['la', 'neige', 'snow', '❄️'],
    ['le', 'vent', 'wind', '💨'],
    ['le', 'nuage', 'cloud', '☁️'],
    ["l'", 'orage', 'storm', '⛈️'],
    ["l'", 'arc-en-ciel', 'rainbow', '🌈'],
    [_, 'il fait chaud', "it's hot", '🥵'],
    [_, 'il fait froid', "it's cold", '🥶'],
    [_, 'il pleut', "it's raining", '☔'],
    ['le', 'printemps', 'spring', '🌱'],
    ["l'", 'été', 'summer', '🏖️'],
    ["l'", 'automne', 'autumn', '🍂'],
    ["l'", 'hiver', 'winter', '⛄'],
    ['le', 'jour', 'day', '🌞'],
    ['la', 'nuit', 'night', '🌃'],
    ['le', 'matin', 'morning', '🌅'],
    ["l'", 'après-midi', 'afternoon', '🕒'],
    ['le', 'soir', 'evening', '🌆'],
    [_, 'aujourd\'hui', 'today', '📅'],
    [_, 'demain', 'tomorrow', '➡️'],
    [_, 'hier', 'yesterday', '⬅️'],
    ['la', 'semaine', 'week', '📆'],
    ['le', 'week-end', 'weekend', '🎉'],
    ['le', 'mois', 'month', '🗓️'],
    ["l'", 'année', 'year', '🎆'],
    ["l'", 'heure', 'hour / time', '🕐'],
    ['la', 'minute', 'minute', '⏱️'],
    [_, 'lundi', 'Monday', _],
    [_, 'mardi', 'Tuesday', _],
    [_, 'mercredi', 'Wednesday', _],
    [_, 'jeudi', 'Thursday', _],
    [_, 'vendredi', 'Friday', _],
    [_, 'samedi', 'Saturday', _],
    [_, 'dimanche', 'Sunday', _],
    ['la', 'lune', 'moon', '🌙'],
    ["l'", 'étoile', 'star', '⭐'],
    ['le', 'ciel', 'sky', '🌌'],
    ['la', 'mer', 'sea', '🌊'],
    ['la', 'plage', 'beach', '🏖️'],
    ['la', 'montagne', 'mountain', '⛰️'],
    ['la', 'forêt', 'forest', '🌲'],
    ["l'", 'arbre', 'tree', '🌳'],
    ['la', 'fleur', 'flower', '🌸'],
    ["l'", 'herbe', 'grass', '🌿'],
    ['la', 'rivière', 'river', '🏞️'],
    ['le', 'feu', 'fire', '🔥'],
    ['la', 'terre', 'earth / ground', '🌍'],
    ['le', 'monde', 'world', '🌎'],
    ['la', 'fête', 'party', '🎉'],
    [_, 'Noël', 'Christmas', '🎄'],
    ['les', 'vacances', 'holidays', '🏝️'],
  ],
  12: [
    [_, 'être', 'to be', '🫵'],
    [_, 'avoir', 'to have', '🤲'],
    [_, 'aller', 'to go', '🚶'],
    [_, 'venir', 'to come', '🫴'],
    [_, 'faire', 'to do / make', '🛠️'],
    [_, 'dire', 'to say', '💬'],
    [_, 'parler', 'to speak', '🗣️'],
    [_, 'voir', 'to see', '👀'],
    [_, 'regarder', 'to look / watch', '👁️'],
    [_, 'écouter', 'to listen', '👂'],
    [_, 'entendre', 'to hear', '🔊'],
    [_, 'manger', 'to eat', '🍽️'],
    [_, 'boire', 'to drink', '🥤'],
    [_, 'dormir', 'to sleep', '😴'],
    [_, 'jouer', 'to play', '🎮'],
    [_, 'lire', 'to read', '📖'],
    [_, 'écrire', 'to write', '✍️'],
    [_, 'chanter', 'to sing', '🎤'],
    [_, 'danser', 'to dance', '💃'],
    [_, 'courir', 'to run', '🏃'],
    [_, 'marcher', 'to walk', '🚶'],
    [_, 'sauter', 'to jump', '🤸'],
    [_, 'nager', 'to swim', '🏊'],
    [_, 'ouvrir', 'to open', '🔓'],
    [_, 'fermer', 'to close', '🔒'],
    [_, 'donner', 'to give', '🎁'],
    [_, 'prendre', 'to take', '✊'],
    [_, 'aimer', 'to like / love', '❤️'],
    [_, 'vouloir', 'to want', '🙏'],
    [_, 'pouvoir', 'to be able / can', '💪'],
    [_, 'savoir', 'to know', '🧠'],
    [_, 'penser', 'to think', '💭'],
    [_, 'apprendre', 'to learn', '🎓'],
    [_, 'comprendre', 'to understand', '💡'],
    [_, 'acheter', 'to buy', '🛒'],
    [_, 'habiter', 'to live (somewhere)', '🏠'],
    [_, 'travailler', 'to work', '💼'],
    [_, 'attendre', 'to wait', '⏳'],
    [_, 'chercher', 'to look for', '🔍'],
    [_, 'trouver', 'to find', '🔎'],
    [_, 'aider', 'to help', '🤝'],
    [_, 'rire', 'to laugh', '😂'],
    [_, 'pleurer', 'to cry', '😭'],
    [_, 'dessiner', 'to draw', '✏️'],
    [_, 'grand', 'big / tall', '🦒'],
    [_, 'petit', 'small / little', '🐜'],
    [_, 'bon', 'good', '👍'],
    [_, 'mauvais', 'bad', '👎'],
    [_, 'beau', 'beautiful / handsome', '🌟'],
    [_, 'joli', 'pretty', '🌸'],
    [_, 'nouveau', 'new', '🆕'],
    [_, 'vieux', 'old', '👴'],
    [_, 'jeune', 'young', '🧒'],
    [_, 'chaud', 'hot', '🔥'],
    [_, 'froid', 'cold', '🧊'],
    [_, 'rapide', 'fast', '🐇'],
    [_, 'lent', 'slow', '🐢'],
    [_, 'fort', 'strong / loud', '💪'],
    [_, 'facile', 'easy', '😌'],
    [_, 'difficile', 'difficult', '😓'],
    [_, 'gentil', 'kind / nice', '🤗'],
    [_, 'méchant', 'mean / naughty', '😈'],
    [_, 'drôle', 'funny', '🤣'],
    [_, 'propre', 'clean', '✨'],
    [_, 'sale', 'dirty', '🧹'],
    [_, 'plein', 'full', '🈵'],
    [_, 'vide', 'empty', '🕳️'],
    [_, 'ouvert', 'open', '🔓'],
    [_, 'fermé', 'closed', '🔒'],
    [_, 'gauche', 'left', '⬅️'],
    [_, 'droite', 'right', '➡️'],
    [_, 'haut', 'high / top', '⬆️'],
    [_, 'bas', 'low / bottom', '⬇️'],
    [_, 'près', 'near', '📍'],
    [_, 'loin', 'far', '🔭'],
  ],
};
